name: Workflow Orchestrator

on:
  push:
    branches:
      - main
      - development
      - 'feature/**'
  pull_request:
    branches:
      - main
      - development
      - 'feature/**'

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI checks
        run: pnpm run ci

      - name: Run tests
        run: pnpm run test

      - name: Build package
        run: pnpm run build

      - name: Validate package for publishing (Dry Run)
        run: pnpm publish --dry-run --filter tableau-extensions-api --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Publish to npm
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: pnpm publish --filter tableau-extensions-api --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
